version: '3.8'

services:
  tigerbeetle:
    build:
      context: .
      dockerfile: tigerbeetle.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - tigerbeetle-data:/data
    security_opt:
      - "seccomp=unconfined"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - finance-api
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/3000' 2>/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - PORT=8080
      - TIGERBEETLE_ADDRESS=tigerbeetle:3000
    depends_on:
      tigerbeetle:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - finance-api

volumes:
  tigerbeetle-data:

networks:
  finance-api:
    driver: bridge 